name: Prepare Version
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  changeset-action:
    name: Run Changeset Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "ðŸ›ƒ Harden the runner (Audit all outbound calls)"
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: "ðŸ›’ Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.GH_PUSH_PROTECTED_KEY }}
          fetch-depth: 0

      - uses: ./.github/templates/node-setup

      - name: Create Pull Request
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: "exit 1" # Fail on publish - Should always only create a PR
          createGithubReleases: false
          title: "chore: update onyx versions and changelogs for release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
