name: Prepare Version
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  pull-requests: write

jobs:
  changeset-action:
    name: Run Changeset Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.GH_PUSH_PROTECTED_KEY }}
          fetch-depth: 0

      - uses: ./.github/templates/node-setup

      - name: Create Pull Request
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          publish: "exit 1" # Fail on publish - Should always only create a PR
          createGithubReleases: false
          title: "chore: update onyx versions and changelogs for release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
