name: Prepare Version
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changeset-action:
    name: Run Changeset Action
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.GH_PUSH_PROTECTED_KEY }}
          fetch-depth: 0

      - uses: ./.github/templates/node-setup

      - name: Create Pull Request
        uses: changesets/action@v1
        with:
          publish: "exit 1" # Fail on publish - Should always only create a PR
          createGithubReleases: false
          title: "chore: update onyx versions and changelogs for release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
